# 项目相关配置
yatou:
  # 名称
  name: YaTou
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/yatou/uploadPath，Linux配置 /home/yatou/uploadPath）
  profile: D:/YaTou/uploadPath
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

